### ISSUE TITLE
Is genotype matrix divided by sqrt(n) in lassosum?

### ISSUE THREAD

**Issue by liupeng2117** [tshmak/lassosum#36]
Dear authors,
From your paper (page3, just above equation (4)), the genotype matrix is first normalized and then divided by sqrt(n), such that R=X^{T}X is the LD matrix, which makes sense to me. However, in the runElnet function in funcions.cpp, the genotype matrix is only normalized (line 660), did the genotype matrix then divided by sqrt(n) afterward? I am trying to understand your implementation of lassosum algorithm, thanks!
Peng

**Comment by tshmak** [comment]
Hi Peng, 
I think the genotype matrix *is* normalized in runElnet. See e.g. https://github.com/tshmak/lassosum/blob/0e44b530c77e862f1b88f9e1fad88fdab44e7827/src/functions.cpp#L610
It runs the armadillo normalise function which scales the vector to have unit norm. (http://arma.sourceforge.net/docs.html#normalise). 
Best, 
Tim
    On Thursday, November 4, 2021, 01:48:03 AM GMT+8, liupeng2117 ***@***.***> wrote:  
 
 


Dear authors,
From your paper (page3, just above equation (4)), the genotype matrix is first normalized and then divided by sqrt(n), such that R=X^{T}X is the LD matrix, which makes sense to me. However, in the runElnet function in funcions.cpp, the genotype matrix is only normalized (line 660), did the genotype matrix then divided by sqrt(n) afterward? I am trying to understand your implementation of lassosum algorithm, thanks!
Peng

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liupeng2117** [comment]
Thanks Tim! Yes,  the genotype matrix is normalized so that each SNP has mean 0 and variance 1. I guess my question is do we need to further divide the matrix by sqrt(n-1) as you did in https://github.com/tshmak/lassosum/blob/0e44b530c77e862f1b88f9e1fad88fdab44e7827/R/lassosumR.R#L42?  If I understand correctly, in this way, X^{T}X becomes LD (correlation) matrix, and X^{T}Y becomes correlation.

**Comment by tshmak** [comment]
No. The "normalisation" procedure implied by the `arma::normalise` function is different from what statisticians mean by normalisation. It forces the column to have unit norm, i.e. that $\sum_i x_i^2 = 1$. Hence, if $x$ is zero-centred, it's variance is $1/n$.

**Comment by liupeng2117** [comment]
I see, thanks for your clarification.
