### ISSUE TITLE
target.res$best.pgs generating NaNs

### ISSUE THREAD

**Issue by littleteacupscu** [tshmak/lassosum#37]
@tshmak thanks for the nice tool I have been used to caculate PRS.
I have a problem with best.pgs generating NaNs.

library(lassosum)
y<- fread("pheno_cov.txt")
cov<- y[,c("FID","IID" ,"sex","byear","genotype_array","PC1","PC2","PC3","PC4","PC5","PC6","PC7","PC8","PC9","PC10")]
target.pheno <- y[,c("FID", "IID", "pho")]
cl <- makeCluster(10)
sum.stat <- "prs_sumstat"
bfile <- "my_bfile"
ld.file <- "EUR.hg19"
ss <- fread(sum.stat)
head(ss)
 # SNP CHR     BP A1 A2      beta       se        p sample
#1: rs3115860   1 753405  A  C  0.013735 0.008693 0.114096  71255
#2: rs2073813   1 753541  A  G -0.017856 0.009096 0.049656  68419
nrow(ss)
#[1]   5067039
ss <- ss[!p == 0]
cor <- p2cor(p = ss$p,
        n =ss$sample,
        sign = ss$beta
        )		
fam <- fread(paste0(bfile, ".fam"))
fam[,ID:=do.call(paste, c(.SD, sep=":")),.SDcols=c(1:2)]
 head(fam)
 set.seed(1234)
out <- lassosum.pipeline(
    cor = cor,
    chr = ss$CHR,
    pos = ss$BP,
    A1 = ss$A1,
    A2 = ss$A2,
    ref.bfile = bfile,
	sample=5000,
    test.bfile = bfile,
    LDblocks = ld.file, 
    cluster=cl
)
# Store the R2 results
target.res <- validate(out, pheno = as.data.frame(target.pheno), covar=as.data.frame(cov))
lasso_score <- target.res$results.table
summary(lasso_score$best.pgs)
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
#-0.3927 -0.0565  0.0027  0.0000  0.0592  0.3293    2071

the sample size for bfile is 330,000
I want to know why 2071 individuasl have NA pgs...
I would be really appreciated for your feedback on this issue.

**Comment by tshmak** [comment]
Have you checked if there are any NAs in the pheno and the covar? 
Tim
    On Thursday, November 25, 2021, 04:53:51 PM GMT+8, littleteacupscu ***@***.***> wrote:  
 
 


@tshmak thanks for the nice tool I have been used to caculate PRS.
I have a problem with best.pgs generating NaNs.

library(lassosum)
y<- fread("pheno_cov.txt")
cov<- y[,c("FID","IID" ,"sex","byear","genotype_array","PC1","PC2","PC3","PC4","PC5","PC6","PC7","PC8","PC9","PC10")]
target.pheno <- y[,c("FID", "IID", "pho")]
cl <- makeCluster(10)
sum.stat <- "prs_sumstat"
bfile <- "my_bfile"
ld.file <- "EUR.hg19"
ss <- fread(sum.stat)
head(ss)

SNP CHR BP A1 A2 beta se p sample

#1: rs3115860 1 753405 A C 0.013735 0.008693 0.114096 71255
#2: rs2073813 1 753541 A G -0.017856 0.009096 0.049656 68419
nrow(ss)
#[1] 5067039
ss <- ss[!p == 0]
cor <- p2cor(p = ss$p,
n =ss$sample,
sign = ss$beta
)
fam <- fread(paste0(bfile, ".fam"))
fam[,ID:=do.call(paste, c(.SD, sep=":")),.SDcols=c(1:2)]
head(fam)
set.seed(1234)
out <- lassosum.pipeline(
cor = cor,
chr = ss$CHR,
pos = ss$BP,
A1 = ss$A1,
A2 = ss$A2,
ref.bfile = bfile,
sample=5000,
test.bfile = bfile,
LDblocks = ld.file,
cluster=cl
)

Store the R2 results

target.res <- validate(out, pheno = as.data.frame(target.pheno), covar=as.data.frame(cov))
lasso_score <- target.res$results.table
summary(lasso_score$best.pgs)

Min. 1st Qu. Median Mean 3rd Qu. Max. NA's

#-0.3927 -0.0565 0.0027 0.0000 0.0592 0.3293 2071

the sample size for bfile is 330,000
I want to know why 2071 individuasl have NA pgs...
I would be really appreciated for your feedback on this issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by littleteacupscu** [comment]
> Have you checked if there are any NAs in the pheno and the covar?  Tim On Thursday, November 25, 2021, 04:53:51 PM GMT+8, littleteacupscu ***@***.***> wrote: @tshmak thanks for the nice tool I have been used to caculate PRS. I have a problem with best.pgs generating NaNs. library(lassosum) y<- fread("pheno_cov.txt") cov<- y[,c("FID","IID" ,"sex","byear","genotype_array","PC1","PC2","PC3","PC4","PC5","PC6","PC7","PC8","PC9","PC10")] target.pheno <- y[,c("FID", "IID", "pho")] cl <- makeCluster(10) sum.stat <- "prs_sumstat" bfile <- "my_bfile" ld.file <- "EUR.hg19" ss <- fread(sum.stat) head(ss) SNP CHR BP A1 A2 beta se p sample #1: rs3115860 1 753405 A C 0.013735 0.008693 0.114096 71255 #2: rs2073813 1 753541 A G -0.017856 0.009096 0.049656 68419 nrow(ss) #[1] 5067039 ss <- ss[!p == 0] cor <- p2cor(p = ss$p, n =ss$sample, sign = ss$beta ) fam <- fread(paste0(bfile, ".fam")) fam[,ID:=do.call(paste, c(.SD, sep=":")),.SDcols=c(1:2)] head(fam) set.seed(1234) out <- lassosum.pipeline( cor = cor, chr = ss$CHR, pos = ss$BP, A1 = ss$A1, A2 = ss$A2, ref.bfile = bfile, sample=5000, test.bfile = bfile, LDblocks = ld.file, cluster=cl ) Store the R2 results target.res <- validate(out, pheno = as.data.frame(target.pheno), covar=as.data.frame(cov)) lasso_score <- target.res$results.table summary(lasso_score$best.pgs) Min. 1st Qu. Median Mean 3rd Qu. Max. NA's #-0.3927 -0.0565 0.0027 0.0000 0.0592 0.3293 2071 the sample size for bfile is 330,000 I want to know why 2071 individuasl have NA pgs... I would be really appreciated for your feedback on this issue. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

there is no NA's in my pheno and cov data. In additon, I tried to caculate prs using LDpre2, and also obtained the same results with 2071' NAs. I wonder if there are something problems accuring in LDblocks among the 2071 individuals?

**Comment by tshmak** [comment]
Perhaps try doing it without the covariates to see if it's related to the covars?

**Comment by littleteacupscu** [comment]
> Perhaps try doing it without the covariates to see if it's related to the covars?

it still has 2071 NAs without covariates...

target.res <- validate(out, pheno = as.data.frame(target.pheno))
365326 out of 367397 samples kept in pheno.
>lasso_score <- target.res$results.table
> summary(lasso_score$best.pgs)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
-0.4032 -0.0709 -0.0116 -0.0144  0.0448  0.3160    2071

**Comment by privefl** [comment]
Missing values in the genotype matrix maybe?

**Comment by littleteacupscu** [comment]
> Missing values in the genotype matrix maybe?

I supposed there is no missing values in genotype matrix after QC and I also used the syntax "G2 <- snp_fastImputeSimple(G)" when I conducted PRS caculation using LDpre2. What'more, I have used other gwas summary data(i.e. CVD or SCZ) to caculate PRS of my testbfile using both lasso and LDpre2, and there were no missing prs cases. However, I get NA's when I use gwas stat  above to caulate psr for corresponding traits.... I can't think of any explanation for the NA's of the 2,000 individuals.

**Comment by tshmak** [comment]
Would you be able to extract the subset with missing PRS as a separate .bfile and try running validate on it and see what error it throws out?

**Comment by privefl** [comment]
If you have issues with LDpred2, you can post at https://github.com/privefl/bigsnpr/issues.

**Comment by littleteacupscu** [comment]
> Would you be able to extract the subset with missing PRS as a separate .bfile and try running validate on it and see what error it throws out?

Relly appreciate your feedback. I found some issues with the 2000 genetic data and have solved it now.
Thank a lot for all reply!  :)

**Comment by privefl** [comment]
It would be very helpful if you could describe what was the issue (and how you solved it), in case others have the same problem.

**Comment by littleteacupscu** [comment]
> It would be very helpful if you could describe what was the issue (and how you solved it), in case others have the same problem.

I tried to extract the subset with missing PRS from bfile as the suggestion and found they didn't exist in my genomic data, which means they have phenotypic data but not genetypic data. It's my fault I didn't check the data first ......ε=(´ο｀*)))
